
name: CI

on: [push]

jobs:
  run-tests:

    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2
    - uses: codecov/codecov-action@v1
    - uses: goanpeca/setup-miniconda@v1.0.2
      with:
        acitvate-environment: ose-code-templates
        environment-file: environment.yml
        python-version: 3.7
    - name: scalar testing with coverage report
      shell: bash -l {0}
      run: |
        export PATH="$PATH:/usr/share/miniconda/bin"
        source .envrc
        pytest  
    - name: parallel testing
      shell: bash -l {0}
      run: |
        export PATH="$PATH:/usr/share/miniconda/bin"
        source .envrc
        # TODO: Calling pytest from the project root directory requires to manually set the current
        # working directory in the MPI process. This results in too much overhead at this point to
        # be worth the flexiblity.
        cd templates/01_embarssingly_parallel_loop
        mpiexec -n 1 -usize 3 pytest --with-mpi --cov=test_integration --cov-report=xml
        mpiexec -n 1 -usize 3 python run.py
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        file: templates/01_embarssingly_parallel_loop/coverage.xml
